// apps/svelte/src/routes/+page.svelte
<script lang="ts">
	import Button from '$lib/components/Button.svelte';
	import Carousel from '$lib/components/Carousel.svelte';

	// Import optimized images for carousel (400px height)
	import img1 from '$lib/assets/1.webp?w=600;800;1200&h=400&format=webp&as=srcset';
	import img2 from '$lib/assets/2.webp?w=600;800;1200&h=400&format=webp&as=srcset';
	import img3 from '$lib/assets/3.webp?w=600;800;1200&h=400&format=webp&as=srcset';
	import img4 from '$lib/assets/4.webp?w=600;800;1200&h=400&format=webp&as=srcset';
	import img5 from '$lib/assets/5.webp?w=600;800;1200&h=400&format=webp&as=srcset';
	import img6 from '$lib/assets/6.webp?w=600;800;1200&h=400&format=webp&as=srcset';

	// Import hero banner optimized
	import bannerSrc from '$lib/assets/banner.webp?w=1440;1920&format=webp&as=srcset';

	// Import circular jellyfish optimized
	import circularJellyfish from '$lib/assets/4.webp?w=400&format=webp';

	const carouselImages = [
		{ srcset: img1, alt: 'Jelly fish' },
		{ srcset: img2, alt: 'Jelly fish' },
		{ srcset: img3, alt: 'Jelly fish' },
		{ srcset: img4, alt: 'Jelly fish' },
		{ srcset: img5, alt: 'Jelly fish' },
		{ srcset: img6, alt: 'Jelly fish' }
	];
</script>

<svelte:head>
	<title>stejs.cz</title>
	<meta name="description" content="This is the stejs.cz website" />
</svelte:head>

<!-- Hero Section -->
<div class="relative w-full">
	<!-- Background Image -->
	<img
		srcset={bannerSrc}
		alt="Jellyfish underwater"
		fetchpriority="high"
		class="absolute inset-0 h-full w-full object-cover"
	/>

	<!-- Content Overlay with Gradient -->
	<div
		class="relative grid min-h-screen w-full content-center bg-gradient-to-r from-black/50 from-30% to-black/0 max-md:from-100% px-4 pt-40 pb-30"
	>
		<div class="mx-auto max-w-3xl">
			<h1 class="mb-4 text-3xl font-bold sm:text-5xl sm:leading-12">
				Discover the Mysteries of the Deep Ocean
			</h1>
			<p class="mb-8 leading-relaxed">
				Explore the wonders beneath the waves. Jellyfish, with their graceful movements and
				vibrant colors, are among the ocean's most mesmerizing creatures.
			</p>
			<Button variant="primary" size="lg">Learn More</Button>
		</div>
	</div>
</div>

<!-- Two-Column Content Section -->
<div class="w-full py-14 sm:py-20">
	<div class="mx-auto flex max-w-3xl flex-col items-start gap-x-8 px-4 sm:flex-row">
		<!-- Image Column -->
		<div class="mb-4 h-28 w-28 overflow-hidden rounded-full sm:mb-0 sm:h-40 sm:w-40 rotate-90">
			<img src={circularJellyfish} alt="Jellyfish close-up" class="h-full w-full object-cover" />
		</div>

		<!-- Text Column -->
		<div>
			<h2 class="mb-4 text-2xl font-bold sm:text-3xl">The Grace of Jellyfish</h2>
			<p class="leading-relaxed">
				These creatures have existed for millions of years, drifting through the ocean currents
				with effortless elegance.
			</p>
		</div>
	</div>
</div>

<!-- Carousel Section -->
<Carousel images={carouselImages} />

<!-- Text Content Section -->
<div class="w-full py-14 sm:py-20">
	<div class="mx-auto max-w-md px-4">
		<p class="mb-4 leading-relaxed">
			Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur
			cupidatat.
		</p>
		<p class="mb-4 leading-relaxed">
			Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa
			sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur
			officia.
		</p>
		<p class="leading-relaxed">
			Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim
			nulla est proident. Nostrud officia pariatur ut officia.
		</p>
	</div>
</div>

// apps/qwik/src/routes/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import { type DocumentHead } from "@builder.io/qwik-city";
import { Button } from "~/components/ui";
import { Carousel } from "@qwik-ui/headless";

import BannerImg from "~/img/banner.webp?h=1080&jsx";
import JellyImg from "~/img/jelly.svg?h=700&format=webp&jsx";
import Img1 from "~/img/1.webp?h=700&jsx";
import Img2 from "~/img/2.webp?h=700&jsx";
import Img3 from "~/img/3.webp?h=700&jsx";
import Img4 from "~/img/4.webp?h=700&jsx";
import Img5 from "~/img/5.webp?h=700&jsx";
import Img6 from "~/img/6.webp?h=700&jsx";

export const carouselImages = [
    { description: "Sample description 1" },
    { description: "Sample description 2" },
    { description: "Sample description 3" },
    { description: "Sample description 4" },
    { description: "Sample description 5" },
    { description: "Sample description 6" },
];

export default component$(() => {
    const currentSlide = useSignal(0);

    return (
        <>
            {/* Hero Section */}
            <div class="relative w-full">
                <BannerImg
                    alt="Hero banner"
                    class="absolute inset-0 h-full w-full object-cover"
                    fetchPriority="high"
                />
                <div class="relative bg-gradient-to-r from-black/50 from-30% to-black/0 px-4 pt-40 pb-30 max-md:from-100%">
                    <div class="mx-auto max-w-3xl text-white">
                        <h1 class="mb-8 text-3xl font-bold sm:text-5xl sm:leading-12">
                            Lorem ipsum,
                            <br/>
                            dolor sit amet
                        </h1>

                        <p class="max-w-md leading-relaxed">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
                            consequatur dolorem doloremque dolores explicabo hic in iusto
                            molestias, nemo odio odit perferendis placeat quae quo ratione sit
                            tenetur velit! Corporis.
                        </p>

                        <Button size="lg" class="mt-8">
                            More than lorem
                        </Button>
                    </div>
                </div>
            </div>

            {/* Jelly Section */}
            <div class="w-full px-4 py-14 sm:py-20">
                <div class="mx-auto max-w-3xl items-center gap-x-8 sm:flex sm:px-4">
                    <div class="mb-14 flex w-full items-center justify-center sm:mb-0">
                        <div class="h-28 w-28 overflow-hidden rounded sm:h-40 sm:w-40">
                            <JellyImg
                                alt="Jelly"
                                class="h-full w-full rotate-12 object-contain"
                            />
                        </div>
                    </div>
                    <div class="mx-auto max-w-lg">
                        <h2 class="mb-4 text-2xl font-bold sm:text-3xl">
                            Lorem ipsum dolor
                        </h2>
                        <p class="leading-relaxed">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
                            consequatur dolorem doloremque dolores explicabo hic in iusto
                            molestias, nemo odio odit perferendis placeat quae quo ratione sit
                            tenetur velit! Corporis.
                        </p>

                        <Button size="lg" class="mt-6">
                            More than lorem
                        </Button>
                    </div>
                </div>
            </div>
            {/* Carousel Section */}
            <div class="w-full bg-blue-900/10 px-4 py-14 sm:py-20">
                <div class="mx-auto max-w-3xl">
                    <Carousel.Root
                        // class="flex flex-col"
                        gap={30}
                        bind:selectedIndex={currentSlide}
                    >
                        <Carousel.Scroller class={"select-none"}>
                            <Carousel.Slide>
                                <Img1 alt={"Image 1"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                            <Carousel.Slide>
                                <Img2 alt={"Image 2"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                            <Carousel.Slide>
                                <Img3 alt={"Image 3"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                            <Carousel.Slide>
                                <Img4 alt={"Image 4"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                            <Carousel.Slide>
                                <Img5 alt={"Image 5"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                            <Carousel.Slide>
                                <Img6 alt={"Image 6"} class={"select-none touch-none"} draggable={false}/>
                            </Carousel.Slide>
                        </Carousel.Scroller>

                        <div class="flex border border-solid border-slate-800">
                            <Carousel.Previous
                                class="cursor-pointer border-r border-inherit px-8 py-4 hover:bg-blue-600/10"
                            >
                                &lt;
                            </Carousel.Previous>

                            <div class="grow p-1 text-center">
                                <p>{carouselImages[currentSlide.value].description}</p>
                                <p class="text-sm text-slate-400">
                                    {currentSlide.value + 1}/{carouselImages.length}
                                </p>
                            </div>

                            <Carousel.Next
                                class="cursor-pointer border-l border-inherit px-8 py-4 hover:bg-blue-600/10"
                            >
                                &gt;
                            </Carousel.Next>
                        </div>
                    </Carousel.Root>
                </div>
            </div>

            {/* Text Section */}
            <div class="w-full px-4 py-14 sm:py-20">
                <div class="mx-auto max-w-3xl">
                    <p class="mx-auto mb-4 max-w-lg leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
                        consequatur dolorem doloremque dolores explicabo hic in iusto
                        molestias, nemo odio odit perferendis placeat quae quo ratione sit
                        tenetur velit! Corporis consectetur adipisicing elit. Ad consequatur
                        dolorem doloremque dolores explicabo hic in iusto molestias, nemo
                        odio odit perferendis placeat quae quo ratione.
                    </p>

                    <p class="mx-auto max-w-lg leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
                        consequatur dolorem doloremque dolores explicabo hic in iusto
                        molestias, nemo odio odit perferendis placeat quae quo ratione sit
                        tenetur velit! Corporis.
                    </p>
                </div>
            </div>
        </>
    );
});

export const head: DocumentHead = {
    title: "Blank | Landing page",
    meta: [
        {
            name: "description",
            content: "Landing page for Blank",
        },
    ],
};
