// apps/qwik/src/components/ui/input-with-prefix.tsx
import { component$, type QwikIntrinsicElements } from "@builder.io/qwik";
import { cn } from "~/lib/utils";

export interface InputWithPrefixProps
  extends Omit<QwikIntrinsicElements["input"], "prefix"> {
  prefix: string;
  inputClass?: string;
  containerClass?: string;
}

/**
 * Compound input with prefix display
 * Design guide: wrapper + prefix + input with shared focus state
 */
export const InputWithPrefix = component$<InputWithPrefixProps>(
  ({ prefix, inputClass, containerClass, class: className, ...props }) => {
    return (
      <div
        class={cn(
          // Wrapper styles from design guide
          "flex",
          "items-center",
          "rounded-md",
          "grow",
          "bg-white/5",
          "pl-3",
          "outline",
          "outline-1",
          "-outline-offset-1",
          "outline-white/10",
          "focus-within:outline-2",
          "focus-within:-outline-offset-2",
          "focus-within:outline-indigo-500",
          containerClass
        )}
      >
        {/* Prefix: text-base text-gray-400 select-none sm:text-sm/6 */}
        <span class="flex select-none items-center text-base text-gray-400 sm:text-sm sm:leading-6">
          {prefix}
        </span>

        {/* Input: block min-w-18 sm:min-w-40 max-sm:w-0 w-0 grow
            bg-transparent py-1.5 pr-3 pl-1 text-base text-white
            placeholder:text-gray-500 focus:outline-none sm:text-sm/6 */}
        <input
          {...props}
          class={cn(
            "block",
            "min-w-0",
            "grow",
            "bg-transparent",
            "py-1.5",
            "pr-3",
            "pl-1",
            "text-base",
            "text-white",
            "placeholder:text-gray-500",
            "focus:outline-none",
            "sm:text-sm",
            "sm:leading-6",
            inputClass,
            className
          )}
        />
      </div>
    );
  }
);

// apps/nextjs/components/ui/input-with-prefix.tsx
import { cn } from "@/lib/utils";
import { InputHTMLAttributes, forwardRef } from "react";

export interface InputWithPrefixProps extends InputHTMLAttributes<HTMLInputElement> {
  prefix: string;
}

const InputWithPrefix = forwardRef<HTMLInputElement, InputWithPrefixProps>(
  ({ className, prefix, ...props }, ref) => {
    return (
      <div className="flex rounded-md bg-white/5 outline outline-1 -outline-offset-1 outline-white/10 has-[input:focus]:outline-2 has-[input:focus]:-outline-offset-2 has-[input:focus]:outline-indigo-500 transition-all w-full">
        <span className="pointer-events-none select-none flex items-center pl-3 text-gray-500 text-sm sm:leading-6 text-base sm:text-sm">
          {prefix}
        </span>
        <input
          ref={ref}
          className={cn(
            "block min-w-0 grow py-1.5 pr-3 pl-0 text-base text-white placeholder:text-gray-500 focus:outline-none sm:text-sm sm:leading-6 bg-transparent",
            className
          )}
          {...props}
        />
      </div>
    );
  }
);

InputWithPrefix.displayName = "InputWithPrefix";

export { InputWithPrefix };
